version: "3.3"
    
services:
  db_vietexpo:
    image: mysql:5.7
    volumes:
      - /data/vietexpo/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - "3307:3306"
      - "33070:33060"
    
  wordpress_vietexpo:
    depends_on:
      - db_vietexpo
    image: wordpress:latest
    volumes:
      - /data/vietexpo/wordpress:/var/www/html
    ports:
      - "8888:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db_vietexpo
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
volumes:
  db_data: {}
  wordpress_data: {}