version: "3.3"
    
services:
  db_tshirt:
    image: mysql:5.7
    volumes:
      - /data/bongbenh/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    
  wordpress_tshirt:
    depends_on:
      - db_tshirt
    image: wordpress:latest
    volumes:
      - /data/bongbenh/wordpress:/var/www/html
    ports:
      - "8100:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3307
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
volumes:
  db_data: {}
  wordpress_data: {}